# incremental: true

title: Arbitrary Definitions

defaults:
  - scope:
      path: "" # all files
    values:
      layout: default
  - scope:
      path: "" # all files
      type: posts
    values:
      layout: post

plugins:
  - jekyll-feed
